apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: web-demo-secretstore
  namespace: web-demo
spec:
  provider:
    aws:
      service: ParameterStore
      # define a specific role to limit access
      # to certain secrets
      # role: arn:aws:iam::123456789012:role/external-secrets
      region: ap-southeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: sa-web-demo