apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-demo-extsecret # name for this externalSecret
  namespace: app-demo
spec:
  refreshInterval: 2m
  secretStoreRef:  # the SecretStore with ServiceAccount to authenticate to AWS
    name: app-demo-secretstore
    kind: SecretStore
  target:  # the Secret to be created on the current namespace that will contain the extracted parameters
    name: app-demo-secret
    creationPolicy: Owner
  dataFrom: # the parameterStore name on where to get the secret values, should be on JSON {"key":"value"} pair format
  - extract:
      key: "/DEMO/app_demo_secrets"